# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'scenes.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1067, 681)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 20, 1045, 668))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(870, 190, 71, 31))
        self.label_5.setStyleSheet(u"")
        self.progressBar = QProgressBar(self.page)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QRect(10, 70, 118, 23))
        self.progressBar.setValue(24)
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(870, 60, 67, 17))
        self.newItemToDo = QTextEdit(self.page)
        self.newItemToDo.setObjectName(u"newItemToDo")
        self.newItemToDo.setGeometry(QRect(330, 520, 161, 31))
        self.saveEvent = QPushButton(self.page)
        self.saveEvent.setObjectName(u"saveEvent")
        self.saveEvent.setGeometry(QRect(870, 160, 89, 25))
        self.subject5 = QLabel(self.page)
        self.subject5.setObjectName(u"subject5")
        self.subject5.setGeometry(QRect(10, 290, 67, 17))
        self.subject3 = QLabel(self.page)
        self.subject3.setObjectName(u"subject3")
        self.subject3.setGeometry(QRect(10, 170, 67, 17))
        self.subject4 = QLabel(self.page)
        self.subject4.setObjectName(u"subject4")
        self.subject4.setGeometry(QRect(10, 230, 81, 16))
        self.addSubject = QPushButton(self.page)
        self.addSubject.setObjectName(u"addSubject")
        self.addSubject.setGeometry(QRect(10, 380, 131, 21))
        self.label_2 = QLabel(self.page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 250, 131, 16))
        self.cal = QCalendarWidget(self.page)
        self.cal.setObjectName(u"cal")
        self.cal.setGeometry(QRect(280, 0, 581, 221))
        self.progressBar_4 = QProgressBar(self.page)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(10, 250, 118, 23))
        self.progressBar_4.setValue(24)
        self.text_event = QTextEdit(self.page)
        self.text_event.setObjectName(u"text_event")
        self.text_event.setGeometry(QRect(870, 20, 171, 31))
        self.subject2 = QLabel(self.page)
        self.subject2.setObjectName(u"subject2")
        self.subject2.setEnabled(True)
        self.subject2.setGeometry(QRect(10, 110, 67, 17))
        self.text_event_2 = QTextEdit(self.page)
        self.text_event_2.setObjectName(u"text_event_2")
        self.text_event_2.setGeometry(QRect(870, 80, 171, 31))
        self.comboBox = QComboBox(self.page)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(870, 120, 181, 31))
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(870, 0, 67, 17))
        self.progress = QLabel(self.page)
        self.progress.setObjectName(u"progress")
        self.progress.setGeometry(QRect(20, 0, 71, 21))
        self.pushButton_2 = QPushButton(self.page)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(500, 560, 81, 31))
        self.pushButton = QPushButton(self.page)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(500, 520, 81, 31))
        self.subject1 = QLabel(self.page)
        self.subject1.setObjectName(u"subject1")
        self.subject1.setGeometry(QRect(10, 50, 67, 17))
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(330, 560, 161, 31))
        self.line = QFrame(self.page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(260, -20, 20, 651))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.progressBar_5 = QProgressBar(self.page)
        self.progressBar_5.setObjectName(u"progressBar_5")
        self.progressBar_5.setGeometry(QRect(10, 310, 118, 23))
        self.progressBar_5.setValue(24)
        self.progressBar_2 = QProgressBar(self.page)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(10, 130, 118, 23))
        self.progressBar_2.setValue(24)
        self.nearestEvent_label = QLabel(self.page)
        self.nearestEvent_label.setObjectName(u"nearestEvent_label")
        self.nearestEvent_label.setGeometry(QRect(430, 250, 421, 16))
        self.listWidget = QListWidget(self.page)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(330, 320, 256, 192))
        self.progressBar_3 = QProgressBar(self.page)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(10, 190, 118, 23))
        self.progressBar_3.setValue(24)
        self.label_7 = QLabel(self.page)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(950, 200, 67, 17))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.button_mainPage = QPushButton(self.page_2)
        self.button_mainPage.setObjectName(u"button_mainPage")
        self.button_mainPage.setGeometry(QRect(20, 470, 111, 21))
        self.pushButton_6 = QPushButton(self.page_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(180, 470, 89, 25))
        self.button_prednaska_link = QPushButton(self.page_2)
        self.button_prednaska_link.setObjectName(u"button_prednaska_link")
        self.button_prednaska_link.setGeometry(QRect(420, 60, 89, 25))
        self.label = QLabel(self.page_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(910, 50, 67, 16))
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(420, 40, 121, 16))
        self.label_13 = QLabel(self.page_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(580, 120, 71, 16))
        self.pushButton_4 = QPushButton(self.page_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(110, 400, 89, 25))
        self.textEdit = QTextEdit(self.page_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(580, 150, 451, 271))
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(580, 40, 67, 17))
        self.listWidget_2 = QListWidget(self.page_2)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(240, 230, 256, 192))
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 70, 67, 17))
        self.pushButton_3 = QPushButton(self.page_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 400, 89, 25))
        self.line_2 = QFrame(self.page_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 80, 1041, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 370, 67, 17))
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 50, 111, 16))
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(790, 50, 67, 16))
        self.button_cviko_link = QPushButton(self.page_2)
        self.button_cviko_link.setObjectName(u"button_cviko_link")
        self.button_cviko_link.setGeometry(QRect(580, 60, 89, 25))
        self.comboBox_2 = QComboBox(self.page_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 365, 86, 25))
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 50, 161, 16))
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"15", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u010cas", None))
        self.saveEvent.setText(QCoreApplication.translate("Form", u"Ulozit", None))
        self.subject5.setText(QCoreApplication.translate("Form", u"VAVA", None))
        self.subject3.setText(QCoreApplication.translate("Form", u"PSI", None))
        self.subject4.setText(QCoreApplication.translate("Form", u"Bezpe\u010dnost", None))
        self.addSubject.setText(QCoreApplication.translate("Form", u"Sekcia predmetov", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Najbli\u017e\u0161ie n\u00e1s \u010dak\u00e1: ", None))
        self.subject2.setText(QCoreApplication.translate("Form", u"Databazy", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Akcia", None))
        self.progress.setText(QCoreApplication.translate("Form", u"Predmety", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Odstanit", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Prida\u0165 ", None))
        self.subject1.setText(QCoreApplication.translate("Form", u"subject1", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u010cerven\u00e9 sa vyma\u017e\u00fa", None))
        self.nearestEvent_label.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Akcia", None))
        self.button_mainPage.setText(QCoreApplication.translate("Form", u"Hlavna strana", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"PushButton", None))
        self.button_prednaska_link.setText(QCoreApplication.translate("Form", u"prednaska", None))
        self.label.setText(QCoreApplication.translate("Form", u"email", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"link na prednasku", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"poznamky", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"Odobrat", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"cviko", None))
        self.label_9.setText("")
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Pridat ulohu", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Sablony", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Kedy v rozvrhu", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"meno", None))
        self.button_cviko_link.setText(QCoreApplication.translate("Form", u"PushButton", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Link na is s predmetom", None))
    # retranslateUi

